name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.10+11

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  draft: ^0.0.12
  equatable: ^2.0.7
  flutter_zustand: ^0.0.5
  go_router: ^17.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  path_provider: ^2.1.5
  animations: ^2.1.1
  simple_animations: ^5.2.0
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  collection: ^1.19.1
  uuid: ^4.5.2
  gap: ^3.0.1
  font_awesome_flutter: ^10.12.0
  rxdart: ^0.28.0
  logger: ^2.6.2
  path: ^1.9.1
  json_annotation: ^4.9.0
  http: ^1.6.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_functions: ^6.0.6
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  draft_builder: ^0.0.12
  build_runner: ^2.7.1
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/
